name: 'EESSI'
description: 'Install the EESSI software stack.'
branding:
  icon: 'server'
  color: 'gray-dark'
inputs:
  eessi_config_package:
    description: 'URL to the EESSI cvmfs config package to install'
    required: false
    default: 'https://github.com/EESSI/filesystem-layer/releases/download/v0.3.0/cvmfs-config-eessi_0.3.0_all.deb'
  run_local_checkout:
    description: 'Run the local checkout of the action and not the main repo code'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - id: install-eessi
      run: |
        if [ "${{ inputs.run_local_checkout }}" == "true" ]; then
          echo "WARNING running local checkout of the action !"
          ln -s github-action-cvmfs/createConfig.sh
          .  github-action-cvmfs/setup-cvmfs.sh local
        else
          ln -s ${{ github.action_path }}/github-action-cvmfs/createConfig.sh ${{ github.action_path }}/createConfig.sh
          ${{ github.action_path }}/github-action-cvmfs/setup-cvmfs.sh
        fi
        echo "BASH_ENV=/cvmfs/pilot.eessi-hpc.org/latest/init/bash" >> $GITHUB_ENV
      shell: bash
      env:
        THIS: ${{ github.action_path }}
        CVMFS_CONFIG_PACKAGE: ${{ inputs.eessi_config_package }}
        CVMFS_HTTP_PROXY: DIRECT
        CVMFS_REPOSITORIES: pilot.eessi-hpc.org
