name: 'EESSI'
description: 'Install the EESSI software stack.'
branding:
  icon: 'server'
  color: 'gray-dark'
inputs:
  eessi_config_package:
    description: 'URL to the EESSI cvmfs config package to install'
    required: false
    default: 'https://github.com/EESSI/filesystem-layer/releases/download/v0.3.0/cvmfs-config-eessi_0.3.0_all.deb'
  run_local_checkout:
    description: 'Run the local checkout of the action and not the main repo code'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Mount EESSI CernVM-FS pilot repository
      uses: cvmfs-contrib/github-action-cvmfs@main
        with:
          cvmfs_config_package: ${{ inputs.eessi_config_package }}
          cvmfs_http_proxy: DIRECT
          cvmfs_repositories: pilot.eessi-hpc.org
    - run: |
        source /cvmfs/pilot.eessi-hpc.org/latest/init/bash 
      shell: bash
      env:
        THIS: ${{ github.action_path }}
