name: Bump version tags
on:
  release:
    types:
      - "created"

jobs:
  tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: fischerscode/tagger@v0.1
        with:
          # The prefix of the semantic tags.
          # Default: ''
          prefix: v
