name: Bump version tags
on:
  release:
    types:
      - "created"
# Declare default permissions as read only.
permissions: read-all
jobs:
  tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          fetch-depth: '0'
      - uses: robinraju/release-downloader@d6de084c58345d09b017e22701dbcf26977cfd14 # v1.6
        with:
          repository: "fischerscode/tagger"
          fileName: "tagger.linux"
          tag: v0.1.0
      - run: |
          # Make sure the tagger is what we expect
          echo "efe6d66750425757e599e586b995a19868e0f6b87428c872abce541df423f9d2 tagger.linux"|sha256sum --check --status
          chmod +x $GITHUB_WORKSPACE/tagger.linux
          $GITHUB_WORKSPACE/tagger.linux move -s -p 'v' ${RELEASE_TAG##*/}
          rm $GITHUB_WORKSPACE/tagger.linux
          repo="https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push "$repo" --tags --force
        shell: bash
        env:
          TOKEN: ${{ github.token }}
          RELEASE_TAG: ${{ github.ref }}
