name: ubuntu_gromacs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# Declare default permissions as read only.
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
    - uses: eessi/github-action-eessi@main
      with:
        eessi_stack_version: '2021.06'
    - name: Test EESSI
      run: |
        cmvfs_config showconfig pilot.eessi-hpc.org
        # GROMACS module is loaded via .envrc
        gmx --version
      shell: bash
    - name: Test caching effect EESSI
      run: |
        gmx --version
      shell: bash
    - name: Test module load
      run: |
        module load CMake
        module list
        cmake --version
      shell: bash
