name: ubuntu_gromacs
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eessi/github-action-eessi@v1
      with:
        eessi_stack_version: '2020.12'
    - name: Test EESSI
      run: |
        module load GROMACS
        gmx --version
      shell: bash
