name: ubuntu_gromacs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eessi/github-action-eessi@main
      with:
        eessi_stack_version: '2021.06'
    - name: Test EESSI
      run: |
        # GROMACS module is loaded via .envrc
        gmx --version
      shell: bash
    - name: Test caching effect EESSI
      run: |
        gmx --version
      shell: bash
    - name: Test module load
      run: |
        module load CMake
        module list
        cmake --version
      shell: bash
