name: ubuntu_gromacs
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ocaisa/github-action-eessi@main
      with:
        run_local_checkout: 'true'
    - name: Test EESSI
      run: |
        module load GROMACS
        gmx --version
      shell: bash
