name: ubuntu
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
    - name: Test EESSI
      run: |
        direnv status
        module avail
      shell: bash
