name: ubuntu
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eessi/github-action-eessi@main
      with:
        run_local_checkout: 'true'
    - name: Test EESSI
      run: |
        direnv status
        module avail
      shell: bash
