name: ubuntu
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ocaisa/github-action-eessi@main
      with:
        run_local_checkout: 'true'
    - name: Test EESSI
      run: |
        source /cvmfs/pilot.eessi-hpc.org/latest/init/bash
