name: ubuntu
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
    - name: Test EESSI
      run: |
        direnv status
        module avail
      shell: bash
