name: ubuntu
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eessi/github-action-eessi@update_cvmfs
      with:
        run_local_checkout: 'true'
    - name: Test EESSI
      run: |
        direnv status
        module avail
      shell: bash
