name: ubuntu_tensorflow
on:
  push:
    branches:
      - main
# Declare default permissions as read only.
permissions: read-all
jobs:
  tensorflow_usage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
    - uses: eessi/github-action-eessi@main
      with:
        eessi_stack_version: '2023.06'
    - name: Test EESSI
      run: |
        # TensorFlow module is loaded via .envrc
        python -c "import tensorflow; print(tensorflow.__version__)"
      shell: bash
    - name: Test caching effect of EESSI
      run: |
        python -c "import tensorflow; print(tensorflow.__version__)"
      shell: bash
    - name: Test module load
      run: |
        module load CMake
        module list
        cmake --version
      shell: bash
